### ISSUE TITLE
Include script examples

### ISSUE THREAD

**Issue by bdw429s** [kris-ellery/coldfusion-codeguide#1]
Include equivalent script examples along with the tags.

**Comment by kris-ellery** [comment]
Will do. I'm trying to figure out if I want to add code examples for each section separately.

**Comment by bdw429s** [comment]
Check out this reference-- it just does the examples side by side on each page.
https://github.com/mhenke/CFML-in-100-minutes/wiki/arrays

**Comment by kris-ellery** [comment]
That is a really nice wiki.

I switched to proper syntax highlighter and adding script sections. I'm doing this purely for fun and own experience.

Thanks for the link!
